---
- name: install java
  hosts: appserver 
  become: yes
  vars: 
    - home_dir: /opt/tomcat 
    - username: tomcat
    - shell_bin: /bin/false
    - version: 9.0.62
    - tomcat_lateat: /opt/tomcat/latest
    
  tasks: 
    - name: update repo and cache  
      ansible.builtin.apt:
        name: "{{ java_package }}"
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: instal java 
      ansible.builtin.package:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: tomcat user add
      ansible.builtin.user:
        create_home: yes
        home: "{{ home_dir }}"
        name: "{{ username }}"
        shell: "{{ shell_bin }}" 
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: download tomcat
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ version }}/bin/apache-tomcat-{{ version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ version }}.tar.gz"
      when: ansible_facts['os_family'] == "Debian"  
    - name: extract tomact file
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ version }}.tar.gz"
        dest: "{{ home_dir }}/"
        creates: "{{ home_dir }}/apache-tomcat-9.0.62" 
        remote_src: yes
      when: ansible_facts['os_family'] == "Debian"  
    - name: create the symlink
      ansible.builtin.file:
        src: "{{ home_dir }}/apache-tomcat-9.0.62" 
        dest: "{{ tomcat_latest }}"
        owner:  "{{ username }}"
        group:  "{{ username }}"
        state: link
      when: ansible_facts['os_family'] == "Debian" 