---
- name: install java
  hosts: appserver 
  become: yes 
  tasks: 
    - name: instal java 
      ansible.builtin.package:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
   