---
- name: install java
  hosts: appserver 
  become: yes
  vars: 
    - home_dir: /opt/tomcat 
    - username: tomcat
    - shell_bin: /bin/false
  tasks: 
    - name: update repo and cache  
      ansible.builtin.apt:
        name: "{{ java_package }}"
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: instal java 
      ansible.builtin.package:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: tomcat user add
      ansible.builtin.user:
        create_home: yes
        home: "{{ home_dir }}"
        name: "{{ username }}"
        shell: "{{ shell_bin }}" 
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: download tomcat
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.62/bin/apache-tomcat-9.0.62.tar.gz"
        dest: "/tmp/apache-tomcat-9.0.62.tar.gz"
      when: ansible_facts['os_family'] == "Debian"   