---
- name: install java
  hosts: appserver 
  become: yes
  vars: 
    - home_dir: /opt/tomcat 
    - user_name: tomcat
    - shell_bin: /bin/false
  tasks: 
    - name: update repo and cache  
      ansible.builtin.apt:
        name: "{{ java_package }}"
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: instal java 
      ansible.builtin.package:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: tomcat user add
      ansible.builtin.user:
        create_home: yes
        home: "{{ home_dir }}"
        name: "{{ user_name }}"
        usename: "{{ user_name }}"
        shell: "{{ shell_bin }}" 
        state: present
      when: ansible_facts['os_family'] == "Debian"

   